mode: 'train'
ARCHITECTURE:
    name: 'ResNet152'

pretrained_model: ""
model_save_dir: "./output/"
classes_num: 6
total_images: 840
save_interval: 1
validate: True
valid_interval: 1
epochs: 10
topk: 5
image_shape: [3, 224, 224]

use_mix: False
use_gpu: False
ls_epsilon: -1

LEARNING_RATE:
    function: 'Piecewise'          
    params:                   
        lr: 0.025               
        decay_epochs: [4, 6, 8]
        gamma: 0.1 

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.000100

TRAIN:
    batch_size: 1
    num_workers: 1
    file_list: "./dataset/vegetables_cls/train_list_shuffle.txt"
    data_dir: "./dataset/vegetables_cls/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        # - RandCropImage:
        #     size: 224
        # - RandFlipImage:
        #     flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

